services:
  - type: web
    name: srigst-interiors
    runtime: python
    buildCommand: "pip install -r srigst2/requirements.txt && cd srigst2 && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd srigst2 && gunicorn srigst2.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false